NET_MONITOR := net_monitor
MY_NET_APP := my_net_app
ROOT:=$(HOME)
NDK_PLATFORM_VER := 14
INSTALL_DIR := /data/tmp

ANDROID_SDK_ROOT:=$(ROOT)/android-sdk-linux
ANDROID_NDK_ROOT:=$(ROOT)/android-ndk-r8d
ANDROID_NDK_HOST:=linux-x86
ANDROID_TARGET:=i686-linux-android
ANDROID_TARGET_ARCH:=x86
ANDROID_TOOLCHAIN:=x86-4.4.3

BINDIR:=$(ANDROID_NDK_ROOT)/toolchains/$(ANDROID_TOOLCHAIN)/prebuilt/$(ANDROID_NDK_HOST)
LIBDIR:=$(ANDROID_NDK_ROOT)/platforms/android-$(NDK_PLATFORM_VER)/arch-$(ANDROID_TARGET_ARCH)/usr/lib
INCDIR:=$(ANDROID_NDK_ROOT)/platforms/android-$(NDK_PLATFORM_VER)/arch-$(ANDROID_TARGET_ARCH)/usr/include
BIN := $(BINDIR)/bin

CPP := $(BIN)/$(ANDROID_TARGET)-g++
CC := $(BIN)/$(ANDROID_TARGET)-gcc
CFLAGS := -I$(INCDIR)
LDFLAGS := -Wl,-rpath-link=$(LIBDIR),-dynamic-linker=/system/bin/linker -L$(LIBDIR)
LDFLAGS += $(LIBDIR)/crtbegin_dynamic.o $(LIBDIR)/crtend_android.o -nostdlib -lc -disable-multilib -lm


all: $(NET_MONITOR) $(MY_NET_APP)

OBJ += $(NET_MONITOR).o

OBJS2 += $(MY_NET_APP).o


$(NET_MONITOR): $(OBJ)
	$(CC) $(LDFLAGS) -o $@ $^
$(MY_NET_APP): $(OBJS2)
	$(CC) $(LDFLAGS) -o $@ $^

%.o: %.c
	$(CC) -c $(INCLUDE) $(CFLAGS) $< -o $@

shell:
	$(ANDROID_SDK_ROOT)/platform-tools/adb shell

run:
	$(ANDROID_SDK_ROOT)/platform-tools/adb shell $(INSTALL_DIR)/


r: $(NET_MONITOR)
	$(ANDROID_SDK_ROOT)/platform-tools/adb push $(NET_MONITOR) $(INSTALL_DIR)
	$(ANDROID_SDK_ROOT)/platform-tools/adb shell chmod 777 $(INSTALL_DIR)/$(NET_MONITOR)

p: $(MY_NET_APP)
	$(ANDROID_SDK_ROOT)/platform-tools/adb push $(MY_NET_APP) $(INSTALL_DIR)
	$(ANDROID_SDK_ROOT)/platform-tools/adb shell chmod 777 $(INSTALL_DIR)/$(MY_NET_APP)

clean:
	@rm -f $(NET_MONITOR) $(MY_NET_APP) $(NET_MONITOR).o $(MY_NET_APP).O
